name: shtak
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  noise_meter: ^5.0.2
  package_info_plus: ^8.1.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  record: ^5.2.0
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/sounds/
    - assets/icon/
    - .env
